// ./scripts/core/dbSchema.js

/**
 * Словник файлів бази даних
 * Об'єкт жорстко зафіксовано в пам'яті.
 */
export const DATA_FILES = Object.freeze({
	basic: "basic.csv",
	birth: "birth.csv",
	death: "death.csv",
	marriage: "marriage.csv",
	names: "names.csv",
	baptism: "baptism.csv",
	funeral: "funeral.csv",
	familyList: "familyList.csv",
	familyRoles: "familyRoles.csv",
	events: "events.csv",
	participants: "participants.csv",
	places: "places.csv",
	churches: "churches.csv",
	cemeteries: "cemeteries.csv",
	coats: "coats.csv",
	archives: "archives.csv",
	records: "records.csv",
	placeNamesHistory: "placeNamesHistory.csv",
	churchAdminHistory: "churchAdminHistory.csv",
	flagsHistory: "flagsHistory.csv",
	education: "education.csv",
	job: "job.csv",
	awards: "awards.csv",
	military: "military.csv",
	gallery: "gallery.csv",
	identity: "identity.csv",
	domicile: "domicile.csv",
	personal: "personal.csv",
	spiritualKinship: "spiritualKinship.csv",
});

/**
 * Словник колонок (COLUMNS) для парсингу CSV
 * Застосовано глибоке заморожування (Deep Freeze) усіх вкладених рівнів.
 */
export const COLUMNS = Object.freeze({
	basic: Object.freeze({
		id: "person_id",
		name: "name",
		surname: "surname",
		patronymic: "patronymic",
		gender: "gender",
		status: "status",
		photo: "photo_id",
		slug: "profile_slug",
		vitalStatus: "vital_status",
	}),
	names: Object.freeze({
		personId: "person_id",
		title: "title",
		altFirstNames: "alt_first_names",
		bSurname: "b_surname",
		baptismName: "baptism_name",
		bNobleNicknames: "b_noble_nicknames",
		bOriginPlace: "b_origin_place",
		bCoat: "b_coat_of_arms",
		altSurnames: "alt_surnames",
		serviceSurname: "service_surname",
		mSurname: "m_surname",
		mNobleNicknames: "m_noble_nicknames",
		mOriginPlace: "m_origin_place",
		mCoat: "m_coat_of_arms",
		deJurePatronymic: "de_jure_patronymic",
	}),
	birth: Object.freeze({
		id: "birth_id",
		personId: "person_id",
		placeId: "place_id",
		day: "b_day",
		month: "b_month",
		year: "b_year",
		time: "b_time",
		calendar: "is_old_style",
		type: "record_type",
		adminDivision: "b_admin_division",
		details: "b_place_details",
		address: "b_place_address",
	}),
	baptism: Object.freeze({
		id: "baptism_id",
		personId: "person_id",
		calendar: "is_old_style",
		day: "c_day",
		month: "c_month",
		year: "c_year",
		dateSort: "date_sort",
		churchId: "church_id",
		placeId: "place_id",
		adminDivision: "c_admin_division",
	}),
	marriage: Object.freeze({
		id: "marriage_id",
		personId: "person_id",
		spouseId: "spouse_id",
		order: "m_number",
		calendar: "is_old_style",
		day: "m_day",
		month: "m_month",
		year: "m_year",
		dateSort: "date_sort",
		unionStatus: "union_status",
		placeId: "place_id",
		churchId: "church_id",
		address: "m_place_address",
		civilDetails: "m_civil_place_details",
		civilAddress: "m_civil_place_address",
		adminDivision: "m_admin_division",
	}),
	death: Object.freeze({
		id: "death_id",
		personId: "person_id",
		calendar: "is_old_style",
		time: "d_time",
		day: "d_day",
		month: "d_month",
		year: "d_year",
		dateSort: "date_sort",
		placeId: "place_id",
		cause: "d_cause",
		adminDivision: "d_admin_division",
		details: "d_place_details",
		address: "d_place_address",
	}),
	funeral: Object.freeze({
		id: "funeral_id",
		personId: "person_id",
		deathId: "linked_death_id",
		calendar: "is_old_style",
		time: "f_time",
		day: "f_day",
		month: "f_month",
		year: "f_year",
		dateSort: "date_sort",
		placeId: "place_id",
		churchId: "church_id",
		cemeteryId: "cemetery_id",
		details: "f_place_details",
		adminDivision: "f_admin_division",
	}),
	familyList: Object.freeze({
		photo: "fam_photo",
		status: "fam_status",
		vitalStatus: "fam_vital_status",
		id: "fam_id",
		title: "fam_title",
		surname: "fam_surname",
		firstName: "fam_first_name",
		patronymic: "fam_patronymic",
		gender: "fam_gender",
		birthDate: "fam_birth_date",
		birthPlace: "fam_birth_place",
		deathDate: "fam_death_date",
		deathPlace: "fam_death_place",
		nobleNickname: "fam_noble_nicknames",
		origin: "fam_origin_place",
		coatOfArms: "fam_coat_of_arms",
		socialStatus: "fam_social_status_job",
		religion: "fam_religion_confession",
		maritalStatus: "fam_marital_status",
		parents: "fam_parents",
		note: "fam_kinship_degree",
		bioUrl: "fam_person_bio_url",
	}),
	familyRoles: Object.freeze({
		personId: "person_id",
		parentsBio: "parents_bio",
		parentsStep: "parents_step",
		parentsAdopted: "parents_adopted",
		grandParentsF: "grandparents_f",
		grandParentsM: "grandparents_m",
		spouses: "spouses",
	}),
	events: Object.freeze({
		eventId: "event_ref_id",
		personId: "linked_person_id",
		eventType: "event_type",
		role: "role_code",
	}),
	participants: Object.freeze({
		id: "p_id",
		photo: "p_photo",
		title: "p_title",
		firstName: "p_first_name",
		surname: "p_surname",
		patronymic: "p_patronymic",
		gender: "p_gender",
		bioUrl: "p_person_bio_url",
		birthDate: "p_birth_date",
		deathDate: "p_death_date",
		birthPlace: "p_birth_place",
		deathPlace: "p_death_place",
		origin: "p_origin_place",
		nobleNickname: "p_noble_nicknames",
		coatOfArms: "p_coat_of_arms",
		socialStatus: "p_social_status_job",
		religion: "p_religion_confession",
		maritalStatus: "p_marital_status",
		kinship: "p_kinship_degree",
	}),
	places: Object.freeze({
		id: "place_id",
		nameHist: "name_hist",
		nameCurrent: "name_current",
		status: "status",
		parentId: "parent_place_id",
		lat: "geo_lat",
		lng: "geo_lng",
		note: "note",
		map: "google_maps_url",
	}),
	placeNamesHistory: Object.freeze({
		placeId: "place_id",
		name: "name_hist",
		dateStart: "year_start",
		dateEnd: "year_end",
	}),
	churches: Object.freeze({
		id: "church_id",
		placeId: "place_id",
		name: "church_name",
		confession: "confession",
		status: "status",
		map: "church_map_url",
		address: "church_address",
	}),
	churchAdminHistory: Object.freeze({
		churchId: "church_id",
		dateStart: "date_start",
		dateEnd: "date_end",
		adminDivision: "c_admin_division",
	}),
	cemeteries: Object.freeze({
		id: "cemetery_id",
		placeId: "place_id",
		name: "cemetery_name",
		address: "cemetery_address",
		status: "status",
		map: "cemetery_map_url",
	}),
	coats: Object.freeze({
		name: "coat_of_arms",
		url: "coat_of_arms_url",
	}),
	archives: Object.freeze({
		id: "archive_id",
		name: "archive_name",
		address: "archive_address",
	}),
	records: Object.freeze({
		id: "record_id",
		personsId: "persons_id",
		type: "type",
		category: "category",
		title: "title",
		year: "year",
		archiveId: "archive_id",
		archiveRef: "archive_ref",
		images: "images",
		transcription: "transcription",
		externalLink: "external_link",
		participants: "participants",
	}),
	flagsHistory: Object.freeze({
		name: "admin_name",
		yearStart: "year_start",
		yearEnd: "year_end",
		file: "flag_file",
	}),
	education: Object.freeze({
		personId: "person_id",
		level: "level",
		institution: "institution",
		institutionLink: "institution_link",
		department: "department",
		direction: "direction",
		qualification: "qualification",
		degree: "degree",
		address: "address",
		period: "period", // Уніфіковано з years
		form: "form",
		document: "document",
	}),
	job: Object.freeze({
		personId: "person_id",
		company: "company",
		position: "position",
		period: "period",
		form: "form",
		companyLink: "company_link",
		facility: "facility",
		address: "address",
		settlement: "settlement",
		region: "region",
		document: "document",
	}),
	awards: Object.freeze({
		personId: "person_id",
		date: "date",
		icon: "icon",
		title: "title",
	}),
	military: Object.freeze({
		personId: "person_id",
		type: "type",
		affiliation: "affiliation",
		branch: "branch",
		rank: "rank",
		position: "position",
		place: "place",
		period: "period",
		participation: "participation",
		recordTitle: "record_title", // Додано
		record: "record", // Додано
		recordUrl: "record_url", // Додано
		archiveId: "archive_id", // Додано
		archiveRef: "archive_ref", // Додано
		desc: "desc", // Додано
	}),
	gallery: Object.freeze({
		personId: "person_id",
		album: "album",
		src: "src",
		subtitle: "subtitle",
	}),
	identity: Object.freeze({
		personId: "person_id",
		estate: "estate",
		belief: "belief",
		citizenship: "citizenship",
		nationality: "nationality",
		languages: "languages",
	}),
	domicile: Object.freeze({
		personId: "person_id",
		type: "type",
		period: "period",
		region: "region",
		settlement: "settlement",
		address: "address",
	}),
	personal: Object.freeze({
		personId: "person_id",
		appearance: "appearance",
		temperament: "temperament",
		lifestyle: "lifestyle",
		hobby: "hobby",
		pets: "pets",
		activity: "activity",
		lifePeriod: "life_period",
		property: "property",
	}),
	spiritualKinship: Object.freeze({
		personId: "person_id",
		targetId: "target_ids",
		roleCode: "role_code",
		eventDate: "event_date",
		eventPlace: "event_place",
	}),
});
